"""MCP subpackage exports."""

from openagent.tools.mcp.auth import McpAuthorizationAdapter, parse_www_authenticate
from openagent.tools.mcp.client_capabilities import (
    McpElicitationBridge,
    McpRootsProvider,
    McpSamplingBridge,
)
from openagent.tools.mcp.errors import (
    McpAuthorizationError,
    McpCapabilityError,
    McpError,
    McpProtocolError,
    McpRemoteToolError,
    McpTransportError,
)
from openagent.tools.mcp.extensions import McpSkillAdapter
from openagent.tools.mcp.models import (
    McpAuthConfig,
    McpAuthMetadata,
    McpAuthState,
    McpClientCapabilities,
    McpElicitationRequest,
    McpListPage,
    McpLogEvent,
    McpPromptDescriptor,
    McpResourceDescriptor,
    McpResourceNotification,
    McpRoot,
    McpSamplingRequest,
    McpServerCapabilities,
    McpServerConnection,
    McpServerDescriptor,
    McpSessionHandle,
    McpTaskHandle,
    McpToolDescriptor,
    McpTransportHandle,
    McpTransportResponse,
)
from openagent.tools.mcp.protocol import (
    InMemoryMcpClient,
    McpProtocolClient,
    TransportBackedMcpClient,
)
from openagent.tools.mcp.runtime import McpPromptAdapter, McpResourceAdapter, McpToolAdapter
from openagent.tools.mcp.transport import (
    HttpTransportConfig,
    InMemoryMcpTransport,
    McpTransport,
    StdioMcpTransport,
    StdioTransportConfig,
    StreamableHttpMcpTransport,
)

__all__ = [
    "HttpTransportConfig",
    "InMemoryMcpClient",
    "InMemoryMcpTransport",
    "McpAuthConfig",
    "McpAuthMetadata",
    "McpAuthState",
    "McpAuthorizationAdapter",
    "McpAuthorizationError",
    "McpCapabilityError",
    "McpClientCapabilities",
    "McpElicitationBridge",
    "McpElicitationRequest",
    "McpError",
    "McpListPage",
    "McpLogEvent",
    "McpPromptAdapter",
    "McpPromptDescriptor",
    "McpProtocolClient",
    "McpProtocolError",
    "McpRemoteToolError",
    "McpResourceAdapter",
    "McpResourceDescriptor",
    "McpResourceNotification",
    "McpRoot",
    "McpRootsProvider",
    "McpSamplingBridge",
    "McpSamplingRequest",
    "McpServerCapabilities",
    "McpServerConnection",
    "McpServerDescriptor",
    "McpSessionHandle",
    "McpSkillAdapter",
    "McpTaskHandle",
    "McpToolAdapter",
    "McpToolDescriptor",
    "McpTransport",
    "McpTransportError",
    "McpTransportHandle",
    "McpTransportResponse",
    "StdioMcpTransport",
    "StdioTransportConfig",
    "StreamableHttpMcpTransport",
    "TransportBackedMcpClient",
    "parse_www_authenticate",
]
