"""Shared package utilities and constants."""

from openagent.shared.layout import (
    DEFAULT_AGENT_DIRECTORY,
    DEFAULT_ROLE_DIRECTORY,
    DEFAULT_ROLE_ID,
    DEFAULT_RUNTIME_AGENT_ID,
    ensure_agent_plugins_root,
    ensure_agent_workspace,
    ensure_directory,
    ensure_session_workspace,
    ensure_subagent_workspace,
    normalize_openagent_root,
    resolve_agent_directory,
    resolve_agent_instance_root,
    resolve_agent_plugins_root,
    resolve_agent_root,
    resolve_agent_root_from_session_root,
    resolve_agent_transcript_path,
    resolve_agent_workspace,
    resolve_cards_root,
    resolve_role_root,
    resolve_roles_root,
    resolve_session_root,
    resolve_session_workspace,
    resolve_sessions_root,
    resolve_subagent_root,
    resolve_subagent_workspace,
    write_subagent_ref,
)
from openagent.shared.paths import resolve_path_env
from openagent.shared.version import SPEC_VERSION, __version__

__all__ = [
    "DEFAULT_AGENT_DIRECTORY",
    "DEFAULT_ROLE_DIRECTORY",
    "DEFAULT_ROLE_ID",
    "DEFAULT_RUNTIME_AGENT_ID",
    "ensure_agent_plugins_root",
    "SPEC_VERSION",
    "__version__",
    "ensure_agent_workspace",
    "ensure_directory",
    "ensure_session_workspace",
    "ensure_subagent_workspace",
    "normalize_openagent_root",
    "resolve_path_env",
    "resolve_agent_instance_root",
    "resolve_agent_plugins_root",
    "resolve_agent_transcript_path",
    "resolve_agent_workspace",
    "resolve_agent_directory",
    "resolve_agent_root",
    "resolve_agent_root_from_session_root",
    "resolve_cards_root",
    "resolve_role_root",
    "resolve_roles_root",
    "resolve_sessions_root",
    "resolve_session_root",
    "resolve_session_workspace",
    "resolve_subagent_root",
    "resolve_subagent_workspace",
    "write_subagent_ref",
]
